development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis #si on veut que Heroku marche on change redis par async
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %> # et on enleve cette ligne
  channel_prefix: LP4B_production #et cet la aussi
